networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.3
    restart: always
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      # Uncomment for debug
      #- "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.auth:/auth/traefik.auth
    command:
      - --api.dashboard=true
      # Uncomment for debug
      #- --api.insecure=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.leresolver.acme.email=${LETS_ENCRYPT_EMAIL}
    labels:
      ## TRAEFIK ROUTER & DASHBOARD
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_HOST}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.tls.certresolver=leresolver
      - traefik.http.services.traefik.loadbalancer.server.port=8080

      ## Global redirect to HTTPS
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https

      ## Middlewares
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

      ## AUTH
      - traefik.http.middlewares.auth.basicauth.usersfile=/auth/traefik.auth

  html-to-tailwind:
    container_name: html-to-tailwind
    image: ghcr.io/ap1969/html-to-tailwind-api
    restart: always
    networks:
      - web
    environment:
      - AUTH_TOKEN=${HTML_TO_TAILWIND_AUTH_TOKEN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.html-to-tailwind.entrypoints=https
      - traefik.http.routers.html-to-tailwind.rule=Host(`tw.embedbuilder.com`)
      - traefik.http.routers.html-to-tailwind.tls.certresolver=leresolver
      - traefik.http.services.html-to-tailwind.loadbalancer.server.port=3000


  uppy-companion:
    container_name: uppy-companion
    image: transloadit/companion
    restart: always
    networks:
      - web
    environment:
      - COMPANION_DATADIR=/mnt/companion-data
      - COMPANION_DOMAIN=comp.embedbuilder.com
      - COMPANION_PROTOCOL=https
      - COMPANION_CLIENT_ORIGINS=https://onlineadmin.dev,https://embedbuilder.com
      - COMPANION_SECRET=${COMPANION_SECRET}
      - COMPANION_DROPBOX_KEY=${COMPANION_DROPBOX_KEY}
      - COMPANION_DROPBOX_SECRET=${COMPANION_DROPBOX_SECRET}
      - COMPANION_GOOGLE_KEY=${COMPANION_GOOGLE_KEY}
      - COMPANION_GOOGLE_SECRET=${COMPANION_GOOGLE_SECRET}
    volumes:
      - ${COMPANION_DATA_DIR:-./companion-data}:/mnt/companion-data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uppy-companion.entrypoints=https
      - traefik.http.routers.uppy-companion.rule=Host(`comp.embedbuilder.com`)
      - traefik.http.routers.uppy-companion.tls.certresolver=leresolver
      - traefik.http.services.uppy-companion.loadbalancer.server.port=3020

  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - plausible-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - plausible-event-data:/var/lib/clickhouse
      - plausible-event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.4
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      # required: https://github.com/plausible/community-edition/wiki/configuration#required
      - BASE_URL=${PLAUSIBLE_BASE_URL}
      - SECRET_KEY_BASE=${PLAUSIBLE_SECRET_KEY_BASE}
      # optional: https://github.com/plausible/community-edition/wiki/configuration#optional
      # registration: https://github.com/plausible/community-edition/wiki/configuration#registration
      - TOTP_VAULT_KEY
      - DISABLE_REGISTRATION
      - ENABLE_EMAIL_VERIFICATION
      # web: https://github.com/plausible/community-edition/wiki/configuration#web
      - HTTP_PORT
      - HTTPS_PORT
      # databases: https://github.com/plausible/community-edition/wiki/configuration#database
      - DATABASE_URL
      - CLICKHOUSE_DATABASE_URL
      # Google: https://github.com/plausible/community-edition/wiki/configuration#google
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      # geolocation: https://github.com/plausible/community-edition/wiki/configuration#ip-geolocation
      - IP_GEOLOCATION_DB
      - GEONAMES_SOURCE_FILE
      - MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION
      # email: https://github.com/plausible/community-edition/wiki/configuration#email
      - MAILER_ADAPTER
      - MAILER_EMAIL
      - MAILER_NAME
      - SMTP_HOST_ADDR
      - SMTP_HOST_PORT
      - SMTP_USER_NAME
      - SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED
      - POSTMARK_API_KEY
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_BASE_URI
      - MANDRILL_API_KEY
      - SENDGRID_API_KEY
    labels:
      - traefik.enable=true
      - traefik.http.routers.plausible.entrypoints=https
      - traefik.http.routers.plausible.rule=Host(`${PLAUSIBLE_HOST}`)
      - traefik.http.routers.plausible.tls.certresolver=leresolver
      - traefik.http.services.plausible.loadbalancer.server.port=8000

  plausible:
    image: plausible/analytics:latest
    restart: always
    depends_on:
      - plausible_db
      - plausible_events_db
    networks:
      - web
    environment:
      - SECRET_KEY_BASE=${PLAUSIBLE_SECRET_KEY_BASE}
      - DISABLE_REGISTRATION=${PLAUSIBLE_DISABLE_REGISTRATION:-false}
      - DISABLE_AUTH=${PLAUSIBLE_DISABLE_AUTH:-false}
      - DATABASE_URL=postgres://postgres:${PLAUSIBLE_DB_PASSWORD}@plausible_db:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible
    volumes:
      - plausible-config:/app/config



volumes:
  plausible-db-data:
  plausible-event-data:
  plausible-event-logs:
  plausible-data: