networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro

  html-to-tailwind:
    container_name: html-to-tailwind
    image: ghcr.io/ap1969/html-to-tailwind-api
    restart: always
    networks:
      - web
    environment:
      - AUTH_TOKEN=${HTML_TO_TAILWIND_AUTH_TOKEN}
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.html-to-tailwind.entrypoints=http"
      - "traefik.http.routers.html-to-tailwind.rule=Host(`tw.embedbuilder.com`)"
      - "traefik.http.services.html-to-tailwind.loadbalancer.server.port=3000"
      # CORS configuration
      - "traefik.http.middlewares.html-to-tailwind-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.html-to-tailwind-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.html-to-tailwind-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.html-to-tailwind-cors.headers.addvaryheader=true"
      - "traefik.http.routers.html-to-tailwind.middlewares=html-to-tailwind-cors"

  uppy-companion:
    container_name: uppy-companion
    image: transloadit/companion
    restart: always
    networks:
      - web
    environment:
      - COMPANION_DATADIR=/mnt/companion-data
      - COMPANION_DOMAIN=comp.embedbuilder.com
      - COMPANION_PROTOCOL=https
      - COMPANION_CLIENT_ORIGINS=https://onlineadmin.dev,https://embedbuilder.com
      - COMPANION_SECRET=${COMPANION_SECRET}
      - COMPANION_DROPBOX_KEY=${COMPANION_DROPBOX_KEY}
      - COMPANION_DROPBOX_SECRET=${COMPANION_DROPBOX_SECRET}
      - COMPANION_GOOGLE_KEY=${COMPANION_GOOGLE_KEY}
      - COMPANION_GOOGLE_SECRET=${COMPANION_GOOGLE_SECRET}
    volumes:
      - ${COMPANION_DATA_DIR:-./companion-data}:/mnt/companion-data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uppy-companion.entrypoints=https
      - traefik.http.routers.uppy-companion.rule=Host(`comp.embedbuilder.com`)
      - traefik.http.routers.uppy-companion.tls.certresolver=leresolver
      - traefik.http.services.uppy-companion.loadbalancer.server.port=3020


